image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo ready to roll'

vscode:
  extensions:
    - scalameta.metals@1.9.2:A7WIUV8jLUKzBJZUjM7zIg==
    - scala-lang.scala@0.4.2:HkCdqnx7jBQQ2Oj2HZ90+w==